name: Build and Publish

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Generate trunkver
        id: trunkver
        uses: crftd-tech/trunkver@main

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # When changing this sequence, sync with TESTING.md

      - name: clean
        run: ./gradlew clean

      - name: lint
        run: ./gradlew detekt

      - name: compile main
        run: ./gradlew classes

      - name: compile test
        run: ./gradlew testClasses

      - name: microtest
        run: ./gradlew check

      - name: package
        run: ./gradlew -Pversion=${{ steps.trunkver.outputs.trunkver }} assemble

      - name: release
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SigningKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SigningPassword }}
        run: ./gradlew -Pversion=${{ steps.trunkver.outputs.trunkver }} publishToSonatype closeAndReleaseSonatypeStagingRepository
