name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: clean
        run: ./gradlew clean

      - name: lint
        run: ./gradlew detekt

      - name: compile main
        run: ./gradlew classes

      - name: compile test
        run: ./gradlew testClasses

      - name: microtest
        run: ./gradlew check

      - name: package
        run: ./gradlew -Pversion=0.0.${{ github.run_number }} assemble

      - name: release
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SigningKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SigningPassword }}
        run: ./gradlew -Pversion=0.0.${{ github.run_number }} publishToSonatype closeAndReleaseSonatypeStagingRepository
